<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ServicioClienteWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/ServicioClienteWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/ServicioClienteWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://WS/">
    <import location="http://localhost:8091/ServicioCliente/ServicioCliente?wsdl" namespace="http://WS/"/>
    <plnk:partnerLinkType name="ServicioClienteLinkType">
        <plnk:role name="ServicioClienteRole" portType="ns:ServicioCliente"/>
    </plnk:partnerLinkType>
</definitions>
