<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Service-PilotoWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/Service-PilotoWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/Service-PilotoWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://tempuri.org/">
    <import location="file:/C:/Users/eljul/Documents/GitHub/SA_Tarea2/EnterpriseServiceBus/App_WebReferences/ServidorPiloto/Service-Piloto.wsdl" namespace="http://tempuri.org/"/>
    <plnk:partnerLinkType name="ServiceSoapLinkType">
        <plnk:role name="ServiceSoapRole" portType="ns:ServiceSoap"/>
    </plnk:partnerLinkType>
</definitions>
